---

- hosts: all
  become: true
  tasks:

    #install on ubuntu
  - name: install apache and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ libapache2-mod-php }}"
      state: latest
      update_cache: yes

